In [3]:
import numpy as np

### Some reminders

In [4]:
c = np.array([[1,2,3],[4,5,6]])
c

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
print(c[1,1]) # Zero indexing means that calling the first row actually refers to the second
print(c[1,:]) # This gives the entire "first" row
print(c[1,1:]) # Picks the first row, then the first column and everything after it
print(c[c.shape[0]-1,:]) # Also gives the entire "first" row, but this is not how you do it


5
[4 5 6]
[5 6]
[4 5 6]


In [11]:
# Back to a larger structure:
a = np.zeros((5,3))
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [13]:
a[1,1] = 777 # one particular element
a[-2:,-2:] = 1 # bottom right corner
print(a)

[[  0.   0.   0.]
 [  0. 777.   0.]
 [  0.   0.   0.]
 [  0.   1.   1.]
 [  0.   1.   1.]]


Row 5 doesn't exist, so counting back from the bottom, row 4 is like -1, row 3 is like -2.

Fencepost problem:
https://en.wikipedia.org/wiki/Off-by-one_error

In [15]:
a[2,:] = a[1,:]/7
print(a)

[[  0.   0.   0.]
 [  0. 777.   0.]
 [  0. 111.   0.]
 [  0.   1.   1.]
 [  0.   1.   1.]]


In [21]:
a[:,0] = a[:,1] + a[:,2] # make the 0th column a sum of the other two columns
print(a)
a[:,0] = np.sum(a[:,1:], axis=1)
print('Another attempt:\n',a)

[[  0.   0.   0.]
 [777. 777.   0.]
 [111. 111.   0.]
 [  2.   1.   1.]
 [  2.   1.   1.]]
Another attempt:
 [[  0.   0.   0.]
 [777. 777.   0.]
 [111. 111.   0.]
 [  2.   1.   1.]
 [  2.   1.   1.]]


In [25]:
c*2 # multiplies every element in the array by the number
c+10 # adds 10 to each element
c+=10 # means c = c+10
print(c)

[[21 22 23]
 [24 25 26]]
